name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # runs daily at midnight
  workflow_dispatch:


jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate GitHub Contribution Snake
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Kaveesha0107
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
